### ISSUE TITLE
(Layout) non-consistent text adjustment on resize

### ISSUE THREAD

**Issue by Juesto** [badanka/Compact#22]
when you resize the game info window the information text gets dragged with the window instead of expanding. which i am unable to see the full text (server name for example)
a similar issue can be seen on avatarless friends list

**Comment by badanka** [comment]
I can't do much to improve the friends list without breaking other things. The skin engine doesn't really use a logical behaviour for this kind of alignment. I should however be able to get the game info window to act a bit more appropriately.

**Comment by Juesto** [comment]
the text issue in game info is actually a bug  i would say. stock skin does let me see the text, in yours the second part of the text goes together with the resize

**Comment by Juesto** [comment]
the text issue in game info is actually a bug  i would say. stock skin does let me see the text, in yours the second part of the text goes together with the resize

**Comment by Juesto** [comment]
I meant this:
(content doesn't matter but if the text is longer it doesnt allow me to see the rest (usually server name) )
default size: 
![image](https://cloud.githubusercontent.com/assets/12691160/17517099/2ed22bd4-5e18-11e6-8923-27b65554e0bd.png)
Resized ones:
![image](https://cloud.githubusercontent.com/assets/12691160/17517068/1300d586-5e18-11e6-8d9c-83c1b6a07e28.png)
![image](https://cloud.githubusercontent.com/assets/12691160/17517078/1c3a9538-5e18-11e6-851c-d840affffa14.png)

**Comment by badanka** [comment]
I've  already said that I would improve the game info window...

**Comment by Juesto** [comment]
okay, thank you, apologies and friends list is actually fine, servers has a blank thing above the tabs

**Comment by badanka** [comment]
Fixed in 1.5.76

**Comment by Juesto** [comment]
it's not fully fixed, sorry
the server name is longer but its not displayed
![image](https://cloud.githubusercontent.com/assets/12691160/19832009/18e73488-9def-11e6-9aa0-571aa206dcb8.png)
